# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
  branches:
    include:
      - master
      - develop
      - feature/*
      - revert-*

pr:
  branches:
    include:
      - master
      - develop
      - feature/*
      - revert-*

jobs:
- job: VS2019
  displayName: VS2019
  pool:
    vmImage: 'windows-latest'

  strategy:
    maxParallel: 4
    matrix:
      Win32_Debug:
        BuildPlatform: 'Win32'
        Configuration: 'Debug'
      Win32_Release:
        BuildPlatform: 'Win32'
        Configuration: 'Release'
      Win64_Debug:
        BuildPlatform: 'x64'
        Configuration: 'Debug'
      Win64_Release:
        BuildPlatform: 'x64'
        Configuration: 'Release'
      ARM64_Debug:
        BuildPlatform: 'ARM64'
        Configuration: 'Debug'
      ARM64_Release:
        BuildPlatform: 'ARM64'
        Configuration: 'Release'

  steps:
  # show environmental variables for debug.
  - script: set
    displayName: Show environmental variables for debug

  - script: cmake -G "Visual Studio 2019" -A  $(BuildPlatform) -S HelloWorld -B workdir
    displayName: cmake

  - script: cmake --build workdir --config $(Configuration)
    displayName: cmake $(BuildPlatform) $(Configuration)
